# Generated by Django 4.2 on 2023-11-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='contact')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fullname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=50)),
                ('birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
